### ISSUE TITLE
Compile error using default (RabbitMQ 3.5.x)

### ISSUE THREAD

**Issue by cm0x4D** [rabbitmq/rabbitmq-auth-backend-amqp#2]
ERL_LIBS=./build/dep-apps erlc -Wall +debug_info -I ./include -pa ebin -o ebin  src/rabbit_auth_backend_amqp.erl
src/rabbit_auth_backend_amqp.erl:105: field auth_backend undefined in record user
src/rabbit_auth_backend_amqp.erl:106: field impl undefined in record user
src/rabbit_auth_backend_amqp.erl:20: Warning: behaviour rabbit_auth_backend undefined
make: **\* [ebin/rabbit_auth_backend_amqp.beam] Error 1

**Comment by cjutzi** [comment]
Simon: I've pulled the latest from RabitMQ umbrella, but not sure how your above comment works.. 
I've tried to make with BRANCH of v3_4_2 but that branch does not appear to live in the repo.. (rabbit MQ's repo) and does not work for your code at all.. 

do you have a quick patch I can look at to modify your code to build against the latest rabbitMQ bits?

My error messages are as follows: 

ERL_LIBS=./build/dep-apps erlc -Wall +debug_info -I ./include -pa ebin -o ebin  src/rabbit_auth_backend_http.erl
src/rabbit_auth_backend_http.erl:44: field auth_backend undefined in record user
src/rabbit_auth_backend_http.erl:45: field impl undefined in record user
src/rabbit_auth_backend_http.erl:20: Warning: behaviour rabbit_auth_backend undefined
make: *** [ebin/rabbit_auth_backend_http.beam] Error 1

**Comment by simonmacmullen** [comment]
@cjutzi: the branch is `rabbitmq_v3_4_2` (note the `v`). Or indeed `rabbitmq_v3_4_3` now. I'll update this for default / 3.5.0 at some point, but note that if you compile it against default you need to run it against default. Finally, if you just want the damn thing to work :-) pick up a  binary from http://www.rabbitmq.com/community-plugins.html
