### ISSUE TITLE
Support RabbitMQ version 3.11?

### ISSUE THREAD

**Issue by csicar** [rabbitmq/rabbitmq-auth-backend-amqp#37]
It seems like the plugin was only recently updated to support rabbitmq 3.9. (https://github.com/rabbitmq/rabbitmq-auth-backend-amqp/commit/d83e3047f18c466499f3f48dbe157d27ec2f575a#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R4)

Are there any plans to make the amqp auth plugin compatible with  rabbitmq 3.11?

**Comment by michaelklishin** [comment]
Virtually nobody uses this plugin. We can update it to support 3.11, it's likely a matter of some metadata/Makefile updates.

**Comment by csicar** [comment]
Thank you the for quick response :)

> Virtually nobody uses this plugin

Ok, seems like I should not rely on this either then and stick to the http plugin instead.


I'd leave this issue open, in case somebody else has the same problem, but feel free to close it.

**Comment by lukebakken** [comment]
@csicar no worries, I'll get a new release out.

**Comment by lukebakken** [comment]
@csicar - https://github.com/rabbitmq/rabbitmq-auth-backend-amqp/releases/tag/v3.11.0
